name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configurar Node.js y pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          pnpm-version: 8

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Construir proyecto
        run: pnpm run build

      - name: Desplegar en Deno
        uses: denoland/deployctl@v1
        with:
          project: algeria-fullstack-dev
          entrypoint: server/entry.mjs
          root: dist
