name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Necesario para la autentificación con Deno Deploy
      contents: read # Necesario para clonar el repositorio

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # ¿No usas npm? Cambia `npm ci` por `yarn install` o `pnpm i`.
      - name: Instalar las dependencias
        run: pnpm i

      # ¿No usas npm? Cambia `npm run build` por `yarn build` o `pnpm run build`.
      - name: Construir Astro
        run: pnpm run build

      - name: Subir a Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: my-deno-project # TODO: sustituir por el nombre del proyecto Deno Deploy
          entrypoint: server/entry.mjs
          root: dist
